### ISSUE TITLE
NoMethodError: undefined method `country_alpha2' for 

### ISSUE THREAD

**Issue by tejashande** [dgilperez/validates_zipcode#10]
I followed the instruction as suggested in Readme.

In my model, I wrote
```
validates :zip_code, zipcode: true
```
But it gave an error suggesting
```
NoMethodError: undefined method `country_alpha2' for 
```
from
```
gems/validates_zipcode-0.0.9/lib/validates_zipcode/validator.rb:27:in `validate_each'
```
Is anything else which I have missed? I don't have any other validation on my model.

**Comment by dgilperez** [comment]
From the README:

> ValidatesZipcode expects the model to have an attribute called country_alpha2 to contain the country code. You can provide your own country_code using :country_code option, or specify which attribute contains this information using :country_code_attribute option.

**Comment by tejashande** [comment]
I missed that part. Thanks for help.
