### ISSUE TITLE
details hash sets :error to the message instead of the validator type

### ISSUE THREAD

**Issue by nrser** [dgilperez/validates_zipcode#23]
When i do

```ruby
validates :post_code, zipcode: true
```

the `record.errors[:post_code]` object looks like

```
#<ActiveModel::Errors:0x000000057dec18 @base=#< ... post_code: "bad!", ...>, @messages={:post_code=>["Invalid ZIP / postal code"]}, @details={:post_code=>[{:error=>"Invalid ZIP / postal code"}]}>
```

where `record.errors[:post_code].details[0]` is `{:error=>"Invalid ZIP / postal code"}` instead of the [Rails standard behvior][1] of the "validator type" symbol (which would be `:invalid_zipcode` in your case) ([example][2]).

[1]: http://guides.rubyonrails.org/active_record_validations.html#working-with-validation-errors-errors-details
[2]: https://github.com/rails/rails/blob/faca40dfd4032bbe2373210255eb7aa1c6527503/activemodel/lib/active_model/validations/presence.rb#L5

This prevents translating the error into anything other than the default locale:

```YAML
# config/locales/zh-CN.yml
zh-CN:
  errors:
    messages:
      invalid_zipcode: 无效邮编号码
```

```ruby
I18n.t "errors.messages.#{ record.errors.details[:post_code].first[:error] }", locale: 'zh-CN'
=> "translation missing: zh-CN.errors.messages.Invalid ZIP / postal code"
```

It's expected to produce a translation as it does with built-in validations:

```ruby
I18n.t "errors.messages.#{ record.errors.details[:name].first[:error] }", locale: 'zh-CN'
=> "不能为空字符"
```

Is there any reason the library is using the string message instead of the "validator type" symbol?

**Comment by dgilperez** [comment]
Closed via #24
