### ISSUE TITLE
Invalid postal code string passes validation for United Arab Emirates 

### ISSUE THREAD

**Issue by eric-norcross** [dgilperez/validates_zipcode#28]
`ValidatesZipcode::Zipcode.new(zipcode: "PO Box 506808", country_alpha2: "AE").valid?` returns `true` but should return `false`

I've been looking around to see if the UAE even has postal codes and have seen mixed responses. For instance, this [wiki page on global postal codes](https://en.wikipedia.org/wiki/List_of_postal_codes) suggests that it does not; however, [this website](https://www.worldatlas.com/aatlas/ctycodes.htm) and [this website](http://www.geopostcodes.com/UAE) seem to suggest that they do. Although, in either case, the string I entered above should still be invalid.

**Comment by dgilperez** [comment]
Thanks! I've did another search and found no liable reference, removed the regex. Just cut 0.0.18 version. 

Please be aware that validations for countries with no support on the gem always validate `true`. This is so to prevent forms from rendering invalid in countries with no support from us or with no code. If you need that particular validation to return `false`, you need to check country code directly or use another different mechanism.
