### ISSUE TITLE
Ireland

### ISSUE THREAD

**Issue by timokleemann** [dgilperez/validates_zipcode#29]
Thanks for this awesome plugin!

Is it just me or do a lot of the **Irish** ZIP codes not validate?

Using Google Maps I randomly picked a few Irish codes and none of them validated:

* X91 PK81
* V94 H2PP
* D07 R6YE

I also tried replacing the blanks with dashes, since some people in Ireland seem to do that. But to no avail.

Is this a bug or am I missing something really fundamental here?

I've never been to Ireland but I read that there was a major postal reform in 2015 where they introduced postal codes for the very first time.

**Comment by dgilperez** [comment]
Thanks! Fixed and released 0.0.19
