### ISSUE TITLE
Valid UK postcode is invalid

### ISSUE THREAD

**Issue by Onumis** [dgilperez/validates_zipcode#31]
Noticed that this UK postcode: `W1K 7DA` which is valid (see: https://postcodes.io/), is raising a validation error.

I've got my model configured with:

`validates :postcode, zipcode: { country_code: :uk }`

Do you think this is a problem with the CLDR database?
What can we do?

**Comment by dgilperez** [comment]
That's probably the case. 

Could you please locate the incorrect regex in a https://github.com/dgilperez/validates_zipcode/blob/master/lib/validates_zipcode/cldr_regex_collection.rb, add a spec covering all valid cases, fix the regex and send a PR?
