### ISSUE TITLE
Document the custom `:message` feature

### ISSUE THREAD

**Issue by harrylewis** [dgilperez/validates_zipcode#47]
Hey @dgilperez, thanks for this awesome gem. I'm currently using it at my job, and I love how easy it is to drop in postal code/zipcode validations using this.

My team is pretty deep into `i18n`, and have our own YAML organization for it. I noticed in `0.2.5`, a feature to allow a custom message was added, which is exactly what my team needs.

My suggestion is around the documentation of this feature. Currently, it is only documented in the CHANGELOG, along with the PR itself. I had to dig around in the code to find out that this was possible.

I'm wondering if it would help others to have this documentation explicitly in the README? I'm sure many others are running custom `i18n` YAML file organizations, so I feel this feature is probably being used pretty heavily.

I don't mind making a PR to suggest something, if you're interested!

**Comment by dgilperez** [comment]
Hi Harry, thanks for your kind words! You are right and I'd love the PR

**Comment by harrylewis** [comment]
Here is the PR #48!

**Comment by dgilperez** [comment]
Superb @harrylewis, thanks a lot 🍻 !

**Comment by harrylewis** [comment]
No problem, @dgilperez, thanks for making the gem! If I have any other suggestions that feature requests in the future, can I go about it in the same way for first creating the issue?

**Comment by dgilperez** [comment]
Yeah, that sounds about right.
