### ISSUE TITLE
Portugal zipcode regex is not correct

### ISSUE THREAD

**Issue by pedrosfdcarneiro** [dgilperez/validates_zipcode#5]
Hy,

The portuguese zipcode regex is incorrect.

It should be like this:

```
\d{4}([\-]\d{3})?
```

So, the following are valid portuguese zipcodes:

```
4500
4500-250
```

Reference: https://en.wikipedia.org/wiki/List_of_postal_codes

Thanks and keep up the good work :+1:

**Comment by dgilperez** [comment]
Fixed and bumped version.

Thanks a lot !!!
