### ISSUE TITLE
Build test data.

### ISSUE THREAD

**Issue by ojsdude** [dgilperez/validates_zipcode#53]
I've introduced your postcode validation into our app; It's fantastic and saved us a lot of headaches!

One thing I'd like to request is that you add a helper for generating postcodes for countries as at the moment I'm using a gem to try to generate one from the regex relating to a country. This is really inconsistent and means that our tests are therefore inconsistent.

A simple object like in https://github.com/dgilperez/validates_zipcode/blob/4e8573f6ca49ccd8da667fd9b0df99366d1e6c6d/lib/validates_zipcode/cldr_regex_collection.rb with a hand full of valid entires for each country would go a long way to help us integrate this with our tests too!

**Comment by ojsdude** [comment]
Looking at https://github.com/dgilperez/validates_zipcode/pull/52 it seems that this method may well exist, but I can't find it anywhere in the code _or_ the documentation so perhaps someone could clarify this for me?

**Comment by dgilperez** [comment]
Hey! That feature is not implemented. I'd be happy to add it if it doesn't add too much weight or any extra dependencies. 

If you're using `faker` gem, you could try `Faker::Base.regexify` with any of the regexs in this library, afaik. I did not test it.

**Comment by dgilperez** [comment]
The gem is pretty stable - postal codes don't churn that much, right? XD - I tend to cut a new release on every meaningful commit, which tends to be just small fixes and regex adjustments. I just forgot to do it with the last PR - you can pull from `master` anyways. 

About the feature itself, I'd be happy to consider a PR as I said - as long as it does not bring extra clutter / dependencies ... would you want to kickstart it?

**Comment by ojsdude** [comment]
OK perfect yeah, I'll get a PR in by 12 pm GMT tomorrow all being well and we can go from there?

Any preference of where to put it? (I'm thinking in https://github.com/dgilperez/validates_zipcode/blob/d9f770695d3aee47d1ad2d51b126cf0f30cca403/lib/validates_zipcode/zipcode.rb)
Any preference of what to call it? (I'm thinking `sample` or `example`)

**Comment by dgilperez** [comment]
Cool!

Yeah, I'd say that class would be perfect. About naming, `sample` sounds
good - what about `generate`?

>

**Comment by dgilperez** [comment]
Closed by https://github.com/dgilperez/validates_zipcode/pull/54
