### ISSUE TITLE
Validating US zipcodes at a state level

### ISSUE THREAD

**Issue by ojsdude** [dgilperez/validates_zipcode#55]
I was wondering if you'd thought about adding validation on postcodes based off of their secondary state level?

I'm thinking mainly the US, but I'd imagine there are other address zip/postal codes that are restricted further by the state, perhaps this is a secondary (optional) state/province code.

**Comment by dgilperez** [comment]
I am unaware of that use case, how does that work on the US?

**Comment by ojsdude** [comment]
[This](http://www.structnet.com/instructions/zip_min_max_by_state.html) is not an extensive list, but it's an example.

It would be a massive challenge for sure, but something that would really help when validating US addresses. It's definitely an extension though and probably something that people should be able to turn on or off until we know for _sure_ there are no edge cases.

**Comment by dgilperez** [comment]
I wonder how general this problem would be, in terms of countries. I am not inclined to support single-country cases, that could escalate quickly. 

About this particular one, it not only seems a challenge to build, but also a hell to maintain - how ofter do those boundaries change, and how can someone keep track of the changes? It may not be practical ... 

Having said that, I am happy to explore a PR that is optional and does not overload the gem. If it does not make it to be merge here, it can always be built as a sister gem, linked from this README.

**Comment by dgilperez** [comment]
This grew old, I am not thinking differently today - I am closing this issue but please feel free to reopen if you have new info / insight.
