### ISSUE TITLE
Validate a zip code outside validators scope

### ISSUE THREAD

**Issue by pedrosfdcarneiro** [dgilperez/validates_zipcode#6]
Hy again :beers:

Is there any public method available to check if a given zip code is valid in a given country?
Something like:

```
ValidatesZipcode.valid?(zipcode, country_code)
```

I'm asking this because in a user register form the zip code is also being validated in the client side with an ajax request.
And in the server, I do something like this:

```
!zip_code.match(ValidatesZipcode::CldrRegexpCollection::ZIPCODES_REGEX[country_code]).nil?
```

which, I think, it's not an ideal solution.

What do you think?

Thanks.

**Comment by dgilperez** [comment]
Hmm not against that at all, I also think that can be handy in a number of situations. 

But just a thought about your ajax validation: Why don't you just check against `valid?` in your server side? Something like this: 

    def ajax_validation
      Address.new(zipcode: zipcode, country: country_code).valid?
    end

**Comment by dgilperez** [comment]
@pedrosfdcarneiro anyway, I still think `ValidatesZipcode.valid?` to be a valuable addition. You have it already in `0.0.8` ! :beers:

**Comment by pedrosfdcarneiro** [comment]
Well, in my case, I couldn't do that because I don't have an *Address* model. That info is stored directily in the *User*.

Good job, once again!
Thanks :smiley:

**Comment by dgilperez** [comment]
`Address` was just an example  :smile:. 

You could always user *your model* to check the validation like this (asuming your model's attribute names): 

`User.new(zipcode: zipcode, country: country_code).tap(&:valid).errors.has_key?(:zipcode)`

Not particularly pretty, but should work ;)

**Comment by pedrosfdcarneiro** [comment]
That's really tricky :open_mouth:

But I think that the ```ValidatesZipcode.valid?``` method is a more elegant solution :smile:
