### ISSUE TITLE
Cambodia Postal Code should be 6 digits

### ISSUE THREAD

**Issue by quenvin** [dgilperez/validates_zipcode#66]
As mentioned in the title. Cambodia(KH) postal code is 6 digits instead of the 5 digits in the regex.

**Comment by dgilperez** [comment]
Thanks @quenvin ! Do you have some public info to check on that? It also helps to keep the reference in here. Do you want to do a PR?

**Comment by quenvin** [comment]
References
https://www.cambodiapostalcode.com/
https://en.wikipedia.org/wiki/List_of_postal_codes

**Comment by dgilperez** [comment]
Fixed!
