### ISSUE TITLE
Greek zipcodes format

### ISSUE THREAD

**Issue by Masa331** [dgilperez/validates_zipcode#9]
Hi,

i'v found that regexp for greek zipcode enforces space betwee third and fourth character - eg "164 25". But in greek yellow pages it's without the space:
http://www.xo.gr/greek-postal-codes-zips/Argyroupoli-Attica/

From where do you take zipcodes regexps? Should i make teh pull request with optional space or without space?

have a greate day,
Masa

**Comment by dgilperez** [comment]
Hey @Masa331!

I was checking your question about regex codes and noticed the link on README was broken. CLDR deprecated postal code regexs, but you can check last version on README: http://unicode.org/cldr/trac/browser/tags/release-27-d05/common/supplemental/postalCodeData.xml

It looks like they updated the regex for Greece, according to your message, so I upgraded it and released 0.0.9. 

Thanks!
